// Writes TODO-CONTENT.md: every placeholder on the built site plus the
// unconfirmed facts in data/. Run with `npm run todo` (builds first).
import fs from "node:fs";
import path from "node:path";
import { ROOT, readJson } from "../lib/load-data.js";

const OUT = path.join(ROOT, "_site");
const decode = (s) => s.replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">");

// 1. Placeholders rendered on each route (data-todo attributes).
const byRoute = new Map();
(function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else if (entry.name.endsWith(".html")) {
      const route = "/" + path.relative(OUT, full).replace(/index\.html$/, "").replace(/\\/g, "/");
      const items = [...fs.readFileSync(full, "utf8").matchAll(/data-todo="([^"]*)"/g)].map((m) => decode(m[1]));
      if (items.length) byRoute.set(route, [...new Set(items)]);
    }
  }
})(OUT);

// 2. Facts in data/ that officers must supply or confirm.
const data = [];
const site = readJson("site.json");
const projects = readJson("projects.json").projects;
const faq = readJson("faq.json");
const team = readJson("team.json");
const alumni = readJson("alumni.json").alumni;
const clients = readJson("past-clients.json").clients;

for (const s of [...site.stats, ...(site.facts || [])]) if (!s.verified) data.push(`site.json → stats/facts: "${s.label}" needs a verified figure.`);
if (!site.recruiting.application_url) data.push("site.json → recruiting.application_url is empty.");
if (!site.recruiting.interest_form_url) data.push("site.json → recruiting.interest_form_url is empty.");
if (!site.links.contact_email) data.push("site.json → links.contact_email: shared club address (never a personal one).");
if (site.images?.hero_is_standin) data.push("site.json → images.hero is a stand-in (campus aerial); supply a wide hero photo that works under a dark overlay.");
if (fs.existsSync(path.join(ROOT, "assets/logos/ey-reversed.png"))) data.push("assets/logos/ey-reversed.png is a generated white version of the EY lockup; replace it with EY's official reversed logo (ideally SVG) if one can be obtained.");
if (site.images?.community_is_standin) data.push("site.json → images.community is the stand-in suits group photo; supply a candid collage of members.");
const testimonials = fs.existsSync(path.join(ROOT, "data/testimonials.json")) ? readJson("testimonials.json").testimonials : [];
if (!testimonials.some((t) => t.consent_to_publish === true)) data.push("Client testimonials: add quotes with written permission to data/testimonials.json to enable the section.");
site.timeline.steps.forEach((s) => { if (!s.date) data.push(`site.json → timeline: date for "${s.name}".`); });
for (const p of projects) {
  const missing = ["approach", "outcome", "image_alt"].filter((k) => p[k] == null || /\[TBD/.test(p[k]));
  if (!p.team?.size) missing.push("team size/roles/majors");
  if (p.fit_inferred) missing.push("confirm 'fits' (currently inferred)");
  if (p.repeat_client_note) missing.push("confirm repeat client");
  if (missing.length) data.push(`projects.json → ${p.id}: ${missing.join(", ")}.`);
}
for (const g of faq.groups) for (const item of g.items) {
  if (item.needs_decision) data.push(`faq.json → "${item.q}" NEEDS DECISION (hidden in production): ${item.decision}`);
  else if (item.needs_review) data.push(`faq.json → "${item.q}" is a draft; officers to review.`);
}
const noConsent = [...team.board, ...team.members, ...alumni].filter((p) => p.consent_to_publish !== true);
data.push(`team.json / alumni.json: ${noConsent.length} entr${noConsent.length === 1 ? "y has" : "ies have"} no consent_to_publish yet and are not shown.`);
const noYear = clients.filter((c) => !c.year).length;
if (noYear) data.push(`past-clients.json: ${noYear} clients have no year; "likely_technical" flags are unconfirmed guesses.`);

const lines = [
  "# Content TODO",
  "",
  `Generated by \`npm run todo\` on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.`,
  "",
  "## Placeholders visible on the site, by page",
  "",
];
// Items on every page (e.g. footer) are listed once.
const pages = [...byRoute.values()];
const everywhere = pages.length ? pages[0].filter((i) => pages.every((list) => list.includes(i))) : [];
if (everywhere.length) lines.push("### Every page", "", ...everywhere.map((i) => `- ${i}`), "");
for (const [route, items] of [...byRoute].sort()) {
  const own = items.filter((i) => !everywhere.includes(i));
  if (own.length) lines.push(`### \`${route}\``, "", ...own.map((i) => `- ${i}`), "");
}
lines.push("## Facts to supply or confirm in `data/`", "", ...data.map((d) => `- ${d}`), "");
fs.writeFileSync(path.join(ROOT, "TODO-CONTENT.md"), lines.join("\n"));
console.log(`[todo] TODO-CONTENT.md: ${[...byRoute.values()].flat().length} placeholders on ${byRoute.size} pages, ${data.length} data items.`);
